/* Generated By:JavaCC: Do not edit this line. KarloffConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KarloffConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int VOID = 6;
  /** RegularExpression Id. */
  int ACHAVES = 7;
  /** RegularExpression Id. */
  int FCHAVES = 8;
  /** RegularExpression Id. */
  int APARENTESES = 9;
  /** RegularExpression Id. */
  int FPARENTESES = 10;
  /** RegularExpression Id. */
  int PONTOVIRGULA = 11;
  /** RegularExpression Id. */
  int ATRIB = 12;
  /** RegularExpression Id. */
  int NVAR = 13;
  /** RegularExpression Id. */
  int NINT = 14;
  /** RegularExpression Id. */
  int SOUT = 15;
  /** RegularExpression Id. */
  int INT = 16;
  /** RegularExpression Id. */
  int NUM = 17;
  /** RegularExpression Id. */
  int ID = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"void\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"=\"",
    "\"newVar\"",
    "\"newInt\"",
    "\"System.output\"",
    "\"integer\"",
    "<NUM>",
    "<ID>",
  };

}
