/* Generated By:JavaCC: Do not edit this line. KarloffConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KarloffConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int VOID = 6;
  /** RegularExpression Id. */
  int ACHAVES = 7;
  /** RegularExpression Id. */
  int FCHAVES = 8;
  /** RegularExpression Id. */
  int APARENTESES = 9;
  /** RegularExpression Id. */
  int FPARENTESES = 10;
  /** RegularExpression Id. */
  int PONTOVIRGULA = 11;
  /** RegularExpression Id. */
  int ATRIB = 12;
  /** RegularExpression Id. */
  int NVAR = 13;
  /** RegularExpression Id. */
  int NINT = 14;
  /** RegularExpression Id. */
  int SOUT = 15;
  /** RegularExpression Id. */
  int INT = 16;
  /** RegularExpression Id. */
  int BOOLEAN = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int THEN = 19;
  /** RegularExpression Id. */
  int WHILE = 20;
  /** RegularExpression Id. */
  int REPEAT = 21;
  /** RegularExpression Id. */
  int UNTIL = 22;
  /** RegularExpression Id. */
  int RETURN = 23;
  /** RegularExpression Id. */
  int SREAD = 24;
  /** RegularExpression Id. */
  int FUNC = 25;
  /** RegularExpression Id. */
  int VIRGULA = 26;
  /** RegularExpression Id. */
  int IGUALA = 27;
  /** RegularExpression Id. */
  int MENOR = 28;
  /** RegularExpression Id. */
  int MAIOR = 29;
  /** RegularExpression Id. */
  int SOMA = 30;
  /** RegularExpression Id. */
  int SUB = 31;
  /** RegularExpression Id. */
  int MULT = 32;
  /** RegularExpression Id. */
  int DIV = 33;
  /** RegularExpression Id. */
  int AND = 34;
  /** RegularExpression Id. */
  int OR = 35;
  /** RegularExpression Id. */
  int NUM = 36;
  /** RegularExpression Id. */
  int ID = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"void\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"=\"",
    "\"newVar\"",
    "\"newInt\"",
    "\"System.output\"",
    "\"integer\"",
    "\"boolean\"",
    "\"if\"",
    "\"then\"",
    "\"while\"",
    "\"repeat\"",
    "\"until\"",
    "\"return\"",
    "\"System.readint\"",
    "\"func\"",
    "\",\"",
    "\"==\"",
    "\"<\"",
    "\">\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "<NUM>",
    "<ID>",
  };

}
